# Created by Giovanni Terlingen
os: osx
osx_image: xcode11.2

before_script:
- (cd $TRAVIS_BUILD_DIR/../; git clone https://github.com/flutter/flutter.git -b stable)
- export PATH=$PATH:$TRAVIS_BUILD_DIR/../flutter/bin
- (flutter config --no-analytics ; flutter config --enable-web ; flutter doctor)
script:
- flutter packages get
- flutter packages pub run build_runner build
- flutter analyze
- flutter build apk
- flutter build ios
